sudo: required

services:
  - docker

script:
  - ./write_version_json.sh
  - docker-compose run test

deploy:
  - provider: script
    script: bash docker_push.sh
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH == "master" || -n "$TRAVIS_TAG"
