version: '3'

services:
  redis:
    container_name: iprepd_redis
    image: redis:3.2
    ports:
      - "6379:6379"

  test:
    container_name: iprepd_app
    image: iprepd:build
    build:
      context: .
    environment:
      - IPREPD_TEST_REDISADDR=redis:6379
    links:
      - redis
    ports:
      - "8080:8080"
    command: bash -c 'cd /go/src/go.mozilla.org/iprepd && go test -v'
