version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Write version.json
          command: ./write_version_json.sh
      - run:
          name: Build containers
          command: make build
      - run:
          name: Run tests
          command: make test
      - run:
         name: Push to Docker Hub
         command: |
           if [[ "${CIRCLE_BRANCH}" == "master" || -n "${CIRCLE_TAG}" ]]; then ./docker_push.sh; fi

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
